---
openapi: 3.0.1
info:
  title: Good Night API
  version: v1
paths:
  "/private/users":
    get:
      summary: Retrieves list of users
      tags:
      - Users
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    attributes:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/api/v1
