default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: good_night_development

test:
  <<: *default
  database: good_night_test

production:
  <<: *default
  database: good_night_production
  username: <%= ENV["DB_PROD_USERNAME"] %>
  password: <%= ENV["DB_PROD_PASSWORD"] %>
